fix(referentialQuestions): fix the referential questions changing not…
XPEHO/xpeapp_admin pull request #130
Opened 2024-12-09 13:52 UTC by Theo-lbg

… working

2024-12-09 14:33 UTC, PiotrFLEURY requested changes
Please consider previous comment

2024-12-09 14:33 UTC, PiotrFLEURY commented on lib/presentation/pages/qvst/widgets/response_reference_widget.dart
> +  }
prefer use provider arguments instead

see [Passing arguments to provider](https://riverpod.dev/fr/docs/essentials/passing_args)

Should be

```dart
final selectedRepo = ref.watch(qvstAnswerRepoListProvider(widget.referenceId));
``` 

init data when you receive other data is not recommended and can cause poor performances on UI

2024-12-10 15:37 UTC, PiotrFLEURY approved these changes
LGTM

2024-12-10 15:44 UTC, NyraSama approved these changes
LGTM

2024-12-10 15:45 UTC, merged